name: Copyright update
on:
    push:
#  schedule:
#    - cron: '00 03 1 1 * *' # Every Jan 1st @ 03:00 UTC
#  To test:
#    - cron: '00 13 24 2 * *'
jobs:
  Update-Copyright-Date:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: update date
      run: |
        last_year=$(date --date='1 year ago' +%Y)
        this_year=$(date +"%Y")
        find . -type f -exec sed -i'' -e "s|2017-${last_year}|2017-${this_year}|g" {} +
    - name: Commit & push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Update copyright year" -m "Workflow: ${{ github.workflow }}, run: ${{ github.run_number }}"
        git push
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "copyright_dates"
        pr_title: 'Updating copyright dates for new year'
        pr_body: |
          Update copyright dates
          - Updated to include the current year
          - Auto-generated by github actions
        pr_reviewer: "Kat-90"
        pr_assignee: "Kat-90"
        github_token: ${{ secrets.GITHUB_TOKEN }}

