name: Copyright update

on:
    push:
#  schedule:
#    - cron: '00 03 1 1 * *'
#  To test:
#    - cron: '00 13 22 2 * *'
jobs:
  Update-Copyright-Date:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update date
      run: |
        last_year=$(date --date='1 year ago' +%Y)
        this_year=$(date +"%Y")
        find . -type f -exec sed -i'' -e 's/2017-${last_year}/2017-${this_year}/g' {} +
    - name: create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3.12.1
      with:
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        commit-message: Update of copyright dates.
        branch: Copyright_dates
        delete-branch: true
        title: 'Updating copyright dates for new year'
        body: |
            Update copyright dates
            - Updated to include the current year
            - Auto-generated by github actions
        assignees: Kat-90
        reviewers: Kat-90
        draft: false
